version: "3.9"
services:
  gateway:
    container_name: gateway
    image: "nginx:stable-bullseye"
    ports:
      - "80:80"
    volumes:
      - ./nginx_gateway.conf:/etc/nginx/conf.d/default.conf

  frontend:
    container_name: frontend
    image: "rachata14/his-finance-frontend:v1"
    expose:
      - "3000"

  backend:
    container_name: backend
    image: "rachata14/his-finance-backend:v1"
    expose:
      - "8000"
    environment:
      - PORT=8000
      - PLUGIN_HOST=plugin
      - PLUGIN_PORT=50001

  plugin:
    container_name: plugin
    image: "rachata14/his-finance-reimbursement:v1"
    expose:
      - "50001"
    environment:
      - PLUGIN_PORT=50001

